import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// notify-brief v1 — Email notification via Resend when brief is generated
Deno.serve(async (req: Request) => {
  const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') ?? '';
  const SYNC_API_KEY = Deno.env.get('SYNC_API_KEY') ?? '';
  const NOTIFY_EMAIL = Deno.env.get('NOTIFY_EMAIL') ?? 'miro@cityage.com';

  const apiKey = req.headers.get('x-sync-key') ?? '';
  if (SYNC_API_KEY && apiKey !== SYNC_API_KEY) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
  if (req.method === 'GET') return new Response(JSON.stringify({ status: 'ok', version: 1, resend_configured: !!RESEND_API_KEY, notify_email: NOTIFY_EMAIL }), { headers: { 'Content-Type': 'application/json' } });
  if (!RESEND_API_KEY) return new Response(JSON.stringify({ error: 'RESEND_API_KEY not set' }), { status: 500 });

  let body: any;
  try { body = await req.json(); } catch { return new Response(JSON.stringify({ error: 'Invalid JSON' }), { status: 400 }); }

  const vertical = body.vertical ?? 'Unknown';
  const briefId = body.brief_id ?? '';
  const preview = body.preview ?? '';
  const articlesUsed = body.articles_used ?? 0;
  const version = body.version ?? '';

  const subject = `\u2709\ufe0f Brief Ready: ${vertical}`;
  const htmlBody = `<div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="border-bottom: 3px solid #1B3A5C; padding-bottom: 12px; margin-bottom: 20px;"><h2 style="margin: 0; color: #1B3A5C;">The Influence Letter</h2><p style="margin: 4px 0 0; color: #666; font-size: 14px;">${vertical}</p></div><p>A new brief has been generated and saved as a draft.</p><table style="width: 100%; border-collapse: collapse; margin: 16px 0;"><tr><td style="padding: 6px 0; color: #888;">Vertical</td><td><strong>${vertical}</strong></td></tr><tr><td style="padding: 6px 0; color: #888;">Articles Used</td><td>${articlesUsed}</td></tr><tr><td style="padding: 6px 0; color: #888;">Brief ID</td><td style="font-family: monospace;">${briefId}</td></tr><tr><td style="padding: 6px 0; color: #888;">Version</td><td>${version}</td></tr></table>${preview ? `<div style="background: #f7f9fb; border-left: 4px solid #1B3A5C; padding: 16px; margin: 20px 0;"><strong style="color: #1B3A5C;">Preview:</strong><br/><br/>${preview.slice(0, 800).replace(/\n/g, '<br/>')}</div>` : ''}<p style="font-size: 13px; color: #999; margin-top: 24px; border-top: 1px solid #eee; padding-top: 12px;">Generated by Signal · urban-planet-brain · The Influence Company</p></div>`;

  try {
    const resp = await fetch('https://api.resend.com/emails', {
      method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${RESEND_API_KEY}` },
      body: JSON.stringify({ from: 'Signal <onboarding@resend.dev>', to: [NOTIFY_EMAIL], subject, html: htmlBody })
    });
    if (!resp.ok) return new Response(JSON.stringify({ error: `Resend error: ${await resp.text()}` }), { status: 500 });
    const result = await resp.json();
    return new Response(JSON.stringify({ success: true, email_id: result.id, to: NOTIFY_EMAIL }), { headers: { 'Content-Type': 'application/json' } });
  } catch (err) { return new Response(JSON.stringify({ error: (err as Error).message }), { status: 500 }); }
});
