import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
import { notFound } from 'next/navigation'

export const revalidate = 60

// Simple markdown-to-HTML for the brief body
function renderMarkdown(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3 class="font-serif font-bold text-xl md:text-2xl text-white mt-10 mb-4">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="font-serif font-bold text-2xl md:text-3xl text-[#D4AF37] mt-6 mb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="font-serif font-black text-3xl md:text-4xl text-white mt-4 mb-2">$1</h1>')
    .replace(/^\*\*(.+?)\*\*$/gm, '<p class="font-sans font-bold text-[#D4AF37] text-sm tracking-wide mt-6 mb-2">$1</p>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-bold text-white">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em class="italic text-[#FDFCF8]/60">$1</em>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener" class="text-[#D4AF37] hover:text-[#D4AF37]/70 underline underline-offset-2">$1</a>')
    .replace(/^---$/gm, '<hr class="border-[#D4AF37]/15 my-8" />')
    .replace(/^(?!<[h|p|s|e|a|u|hr])(.*\S.*)$/gm, '<p class="font-serif text-[#FDFCF8]/80 text-base md:text-lg leading-relaxed mb-4">$1</p>')
}

export default async function BriefPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()

  const { data: brief } = await supabase
    .from('briefs')
    .select('*')
    .eq('id', id)
    .eq('status', 'published')
    .single()

  if (!brief) notFound()

  const date = new Date(brief.published_at).toLocaleDateString('en-CA', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'America/Toronto'
  })

  const html = renderMarkdown(brief.body)

  return (
    <main className="min-h-screen bg-[#050505] text-white">
      {/* Nav */}
      <div className="px-8 md:px-16 py-6 border-b border-[#D4AF37]/20 flex items-center justify-between">
        <Link href="/dispatches" className="font-mono text-[10px] tracking-[0.35em] text-[#D4AF37] uppercase hover:text-[#D4AF37]/80">
          ← All Dispatches
        </Link>
        <span className="font-mono text-[10px] tracking-[0.2em] text-[#888888] uppercase">
          {brief.vertical}
        </span>
      </div>

      {/* Brief content */}
      <article className="max-w-3xl mx-auto px-8 py-12 md:py-16">
        <div className="mb-8">
          <span className="font-mono text-[10px] tracking-[0.3em] text-[#D4AF37] uppercase">
            {brief.vertical}
          </span>
          <span className="font-mono text-[10px] text-[#888888] mx-3">·</span>
          <span className="font-mono text-[10px] tracking-[0.2em] text-[#888888] uppercase">
            {date}
          </span>
        </div>

        <div
          className="brief-content"
          dangerouslySetInnerHTML={{ __html: html }}
        />

        <div className="mt-16 pt-8 border-t border-[#D4AF37]/15">
          <p className="font-mono text-[10px] tracking-[0.2em] text-[#888888] uppercase">
            Generated by {brief.model_used} · Published {date}
          </p>
        </div>
      </article>
    </main>
  )
}
