import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { MagazineFooter } from '@/components/magazine-footer'

export const revalidate = 60

function renderMarkdown(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3 class="font-serif font-bold text-xl md:text-2xl text-black mt-10 mb-4">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="font-serif font-bold text-2xl md:text-3xl text-[#1A365D] mt-6 mb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="font-serif font-black text-3xl md:text-4xl text-black mt-4 mb-2">$1</h1>')
    .replace(/^\*\*(.+?)\*\*$/gm, '<p class="font-mono font-bold text-[#C5A059] text-sm tracking-wide mt-6 mb-2 uppercase">$1</p>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-bold text-black">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em class="italic text-black/60">$1</em>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener" class="text-[#1A365D] hover:text-[#C5A059] underline underline-offset-2">$1</a>')
    .replace(/^---$/gm, '<hr class="border-black/10 my-8" />')
    .replace(/^(?!<[h|p|s|e|a|u|hr])(.*\S.*)$/gm, '<p class="font-serif text-black/80 text-base md:text-lg leading-relaxed mb-4">$1</p>')
}

export default async function BriefPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()

  const { data: brief } = await supabase
    .from('briefs')
    .select('*')
    .eq('id', id)
    .eq('status', 'published')
    .single()

  if (!brief) notFound()

  const date = new Date(brief.published_at).toLocaleDateString('en-CA', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    timeZone: 'America/Toronto'
  })

  const html = renderMarkdown(brief.body)

  return (
    <div className="min-h-screen flex flex-col bg-[#F9F9F7]">
      {/* Compact nav */}
      <header className="border-b border-black bg-[#F9F9F7] px-6 md:px-12 py-5">
        <div className="max-w-[900px] mx-auto flex items-center justify-between">
          <Link href="/" className="font-serif font-black text-2xl uppercase monocle-wordmark hover:text-[#C5A059] transition-colors">
            CityAge
          </Link>
          <Link href="/dispatches" className="font-mono text-[10px] tracking-[0.3em] text-[#C5A059] uppercase hover:text-black transition-colors">
            ← All Dispatches
          </Link>
        </div>
      </header>

      {/* Brief content */}
      <article className="flex-grow max-w-[700px] mx-auto w-full px-6 py-12 md:py-16">
        <div className="mb-8 pb-6 border-b border-black/10">
          <div className="flex items-center gap-3 mb-4">
            <span className="font-mono text-[10px] font-bold tracking-[0.3em] text-[#C5A059] uppercase">
              {brief.vertical}
            </span>
            <span className="font-mono text-[10px] text-black/30">·</span>
            <span className="font-mono text-[10px] tracking-[0.2em] text-black/40 uppercase">
              {date}
            </span>
          </div>
          <h1 className="font-serif font-black text-3xl md:text-4xl leading-tight tracking-tight">
            {brief.title}
          </h1>
        </div>

        <div
          className="brief-content"
          dangerouslySetInnerHTML={{ __html: html }}
        />

        <div className="mt-16 pt-8 border-t border-black/10">
          <p className="font-mono text-[10px] tracking-[0.2em] text-black/30 uppercase">
            Generated by {brief.model_used} · Published {date}
          </p>
        </div>
      </article>

      <MagazineFooter />
    </div>
  )
}
